// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbpgmiuvdzdpvejwclhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZicGdtaXV2ZHpkcHZlandjbGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTMyMjYsImV4cCI6MjA3MjI2OTIyNn0.lfPcqOyvJE-3lEohNWeUUkgH1KfH7QH22Ma9IK1t2XM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});